services:                           # サービスを定義しますという決まり文句
  open_interpreter:                           # pythonという名前でサービスを定義
    image: open_interpreter             # イメージのREPOSITORY名:TAG名を指定
    build: .                        # Dockerfileを相対パスで指定
    container_name: open_interpreter    # 作成されるコンテナ名を指定
    working_dir: /workspace/src     # 作業ディレクトリを指定
    volumes:                        # マウントするファイルを指定する
      - ../src:/workspace/src       # ローカルPCのsrc:コンテナのworkspace/src
    tty: true                       # コンテナを起動し続ける
