services:                           # サービスを定義しますという決まり文句
  langchain:                           # langchainという名前でサービスを定義
    image: langchain             # イメージのREPOSITORY名:TAG名を指定
    build: .                        # Dockerfileを相対パスで指定
    container_name: langchain    # 作成されるコンテナ名を指定
    working_dir: /workspace/src     # 作業ディレクトリを指定
    volumes:                        # マウントするファイルを指定する
      - ../src:/workspace/src       # ローカルPCのsrc:コンテナのworkspace/src
    tty: true                       # コンテナを起動し続ける
